[project]
name = "uv-dcrsystem-train"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pynput>=1.8.1",
    "ultralytics>=8.3.217",
]
